### ISSUE TITLE
Celluloid

### ISSUE THREAD

**Issue by pcercuei** [fazekmar/yastm#1]
It would be great to have support for launching Celluloid (ex gnome-mpv) instead of the regular MPV.

**Comment by fazekmar** [comment]
I was thinking about it.
Basically to add another player support is easy, but all player has a different options, etc and these are all "difficult" to handle.
I can prepare the code to support multiple players but I don't want to add any other because I don't use it I can't guarantee it will work (so I need help for the integrations).

There is an easy solution, I add a simple textbox where you can add any command with command line parameters (and hide the mpv specific settings) but I have security concerns with it. If anybody has able to change this settings it can run any malicious code in your computer so I don't support this idea.

**Comment by pcercuei** [comment]
A simple texbox would be fine. There shouldn't be any security risk, as long as it cannot be changed remotely.

**Comment by fazekmar** [comment]
Because the multi player support is a good idea and I already started the options page refactor in January I add the support in a proper mode.

My plan is to create drop-down list for the players with predefined commands and a free form for the other options.
